export const styleSheet = {
    searchBar: {
        height: '10vh',
        width: '83.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        //border: '2px solid #eeeff1',
        overflowX:'hidden',
        overflowY:'hidden',
        //border:'1px solid red',
    },
    subContainer:{
        height: '100vh',
        width: '83.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft:'11px',
        //border: '2px solid #eeeff1',
        //border:'1px solid red',
        overflowY:'hidden',
    },
    card:{
        height: '98vh',
        width: '50vw',
        //backgroundColor: 'black',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
    },
    chat:{
        height: '98vh',
        width: '33vw',
        //backgroundColor: 'red',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'row',
    },
    chatBox:{
        height: '45vh',
        width: '30vw',
        backgroundColor: '#eeeff1',
        borderRadius:'15px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        //marginTop:'-40px',
        flexWrap: 'wrap',
        flexDirection: 'row',
    },
    chatBoxMan:{
        width:'30vw',
        height:'20vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //border: '1px solid red',
    },
    subChatBoxMan:{
        height: '45vh',
        width: '30vw',
        backgroundColor: '#eeeff1',
        borderRadius:'15px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
    },
    subCard:{
        height: '30vh',
        width: '50vw',
        //backgroundColor: 'black',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
    },
    subCardDetails:{
        height: '68vh',
        width: '50vw',
        //backgroundColor: 'red',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
    },
    card1:{
        height: '16vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#00b894'
    },
    card2:{
        height: '16vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#00cec9'
    },
    card3:{
        height: '16vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#0984e3'
    },
    app:{
        fontFamily: 'sans-serif',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '70vh',
        width: '50vw',
        flexWrap: 'wrap',
        flexDirection: 'row',
    },
    appItem:{
        height: '400px',
        width:'300px',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        //marginBottom:'100px',
        borderRadius:'15px',
        backgroundColor: '#eeeff1',
        
    },

}