export const styleSheet ={
    container: {
        height:'100vh',
        width:'83.5vw',
        marginLeft:'9px',
        overflowX:'hidden',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchBar: {
        height: '15vh',
        width: '83.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        overflowX:'hidden',
        overflowY:'hidden',
        //border:'1px solid red',
    },
    bookingPanel: {
        height: '15vh',
        width: '83.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        //backgroundColor: 'yellow',
    },
    subContainer:{
        height: '85vh',
        width: '83.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        border: '2px solid #eeeff1',
    },
    table1:{
        height: '100vh',
        width: '83.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        //alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        //border: '1px solid red',
    },
    table2:{
        height: '100vh',
        width: '83.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        //alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        //border: '1px solid red',
    }
}