export const styleSheet = {
    container: {
        //border:'1px solid red',
    },
    searchBar: {
        height: '10vh',
        width: '83vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        overflowX:'hidden'
        //border:'1px solid red',
    },
    subContainer:{
        height: '90vh',
        width: '83vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        //border:'1px solid red',
    },
    card:{
        height: '20vh',
        width: '84vw',
        backgroundColor: 'black',
    },
    driverContainer:{
        height: '70vh',
        width: '84vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'row',
        //backgroundColor: 'red',
    },
    app:{
        fontFamily: 'sans-serif',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '70vh',
        width:'83vw',
        flexWrap: 'wrap',
        flexDirection: 'row',
        border: '2px solid #eeeff1',
    },
    appItem:{
        height: '400px',
        width:'350px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'row',
        backgroundColor: 'red',
    }
   
}