export const styleSheet = {
    container: {
        //border:'1px solid red',
        marginLeft:'10px'
    },
    searchBar: {
        height: '10vh',
        width: '82.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        overflowX:'hidden'
        //border:'1px solid red',
    },
    subContainer:{
        height: '90vh',
        width: '82.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        //border:'1px solid red',
    },
    card:{
        height: '20vh',
        width: '82.5vw',
        //backgroundColor: 'black',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
    },
    card1:{
        height: '16vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#00b894'
    },
    card2:{
        height: '16vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#00cec9'
    },
    card3:{
        height: '16vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#0984e3'
    },
    card4:{
        height: '16vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#6c5ce7'
    },
    driverContainer:{
        height: '70vh',
        width: '41vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'row',
        //border: '2px solid #eeeff1',
        //backgroundColor: 'white',
        //backgroundColor: 'red',
    },
    driverSubContainer:{
        height: '65vh',
        width: '40vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
        marginLeft:'10px',
        backgroundColor: '#eeeff1',
        borderRadius:'15px'
    },
    chatBox:{
        height: '21.5vh',
        width: '40vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
    },
    image:{
        height: '21.5vh',
        width: '10vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
    },
    details:{
        height: '21.5vh',
        width: '30vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
    },
    app:{
        fontFamily: 'sans-serif',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '70vh',
        width: '82.5vw',
        flexWrap: 'wrap',
        flexDirection: 'row',
    },
    appItem:{
        height: '400px',
        width:'350px',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        //marginBottom:'100px',
        borderRadius:'15px',
        backgroundColor: '#eeeff1',
    }
   
}