export const styleSheet = {
    container: {
        height:'100vh',
        width:'83.5vw',
        marginLeft:'9px',
        overflowX:'hidden',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchBar: {
        height: '15vh',
        width: '83vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    bookingPanel: {
        height: '15vh',
        width: '83vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        //backgroundColor: 'yellow',
    },
    table: {
        height: '50vh',
        width: '83vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
        //border: '2px solid #eeeff1',
    },
    details:{
        height: '70vh',
        width: '83vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        //border: '1px solid red',
    },
    textContainer:{
        height: '65vh',
        width: '36vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: '#eeeff1',
        //border: '1px solid red',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius:'15px',
        marginLeft:'-20px'
    },
    upload:{
        height: '70vh',
        width: '40vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        //backgroundColor: 'gray'
        //border: '1px solid red',
        marginLeft:'550px',
        marginTop:'-500px'
    }
}