export const styleSheet = {
    container: {
        height:'100vh',
        width:'83.5vw',
        marginLeft:'10px',
        overflowX:'hidden',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchBar: {
        height: '15vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    bookingPanel: {
        height: '15vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        //backgroundColor: 'yellow',
    },
    table: {
        height: '85vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    tableBtn:{
        height: '10vh',
        width: '83.3vw',
        display: 'flex',
        backgroundColor: 'white',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        
    }
}