export const styleSheet = {
    container: {
        //border:'1px solid red',
        marginLeft:'10px',
        marginLeft:'250px',
        overflowX:'hidden',
        overflowY:'hidden'
    },
    searchBar: {
        height: '10vh',
        width: '82.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        overflowX:'hidden'
        //border:'1px solid red',
    },
    subContainer:{
        height: '90vh',
        width: '82.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        //border:'1px solid red',
    },
    searchShedule:{
        height: '15vh',
        width: '82.5vw',
        //backgroundColor: 'black',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
    },
    driverContainer:{
        height: '75vh',
        width: '82.5vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'column',
        border: '2px solid #eeeff1',
        //backgroundColor: 'white',
        //backgroundColor: 'red',
    },
    sheduleTable:{
        height: '70vh',
        width: '50vw',
        backgroundColor: '#eeeff1',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'row',
        borderRadius:'15px'
    },
    sheduleDetail:{
        height: '70vh',
        width: '30vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'row',
    }
   
}