export const styleSheet ={
    container: {
        height:'100vh',
        width:'83.5vw',
        marginLeft:'9px',
        overflowX:'hidden',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchBar: {
        height: '15vh',
        width: '83.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        overflowX:'hidden',
        overflowY:'hidden',
        //border:'1px solid red',
    },
    bookingPanel: {
        height: '15vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        //backgroundColor: 'yellow',
    },
    subContainer: {
        height: '85vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    chart:{
        height: '84vh',
        width: '41.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        //backgroundColor: 'black',
    },
    SubChart:{
        height: '60vh',
        width: '41.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop:'50px'
        //border:'1px solid red'
    },
    incomes:{
        height: '84vh',
        width: '41.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        //backgroundColor:'red'
    },
    chart1:{
        height: '42vh',
        width: '41.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        border:'1px solid red'
    },
    chart2:{
        height: '42vh',
        width: '41.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        border:'1px solid red'
    },
    chart3:{
        height: '42vh',
        width: '41.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        border:'1px solid red'
    }
}
