export const styleSheet ={
    container: {
        height:'100vh',
        width:'83.5vw',
        marginLeft:'9px',
        overflowX:'hidden',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchBar: {
        height: '15vh',
        width: '83.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        overflowX:'hidden',
        overflowY:'hidden',
        //border:'1px solid red',
    },
    bookingPanel: {
        height: '15vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        //backgroundColor: 'yellow',
    },
    subContainer: {
        height: '85vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    card:{
        height: '25vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        //backgroundColor: 'red',
    },
    chart:{
        height: '60vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        //backgroundColor: 'black',
    },
    subCard:{
        height: '25vh',
        width: '83.3vw',
        //backgroundColor: 'black',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'row',  
    },
    card1:{
        height: '15vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#00b894',
    },
    card2:{
        height: '15vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#00cec9'
    },
    card3:{
        height: '15vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#0984e3'
    },
    card4:{
        height: '15vh',
        width: '15vw',
        borderRadius:'15px',
        backgroundColor:'#0984e3'
    },
    SubChart:{
        height: '60vh',
        width: '41.5vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        border:'1px solid red'
    },
}
