export const styleSheet = {
    container: {
        height:'100vh',
        width:'83.5vw',
        marginLeft:'9px',
        overflowX:'hidden',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchBar: {
        height: '10vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    bookingPanel: {
        height: '10vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        //backgroundColor: 'yellow',
    },
    vehicleCard:{
        height: '90vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
}