export const styleSheet = {
    container: {
        height:'100vh',
        width:'83.5vw',
        marginLeft:'9px',
        overflowX:'hidden',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
        // marginLeft:'250px',
        // overflowX:'hidden',
        // overflowY:'hidden'
    },
    searchBar: {
        height: '10vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    bookingPanel: {
        height: '10vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        //backgroundColor: 'yellow',
    },
    table: {
        height: '55vh',
        width: '83vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
        //border: '2px solid #eeeff1',
    },
    details:{
        height: '70vh',
        width: '83vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        //border: '2px solid #eeeff1',
    },
    textContainer:{
        height: '65vh',
        width: '38vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius:'15px',
        marginLeft:'20px'
    },
    upload:{
        height: '70vh',
        width: '41vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        //backgroundColor: 'gray'
    }
}