export const styleSheet = {
    container:{
        height: '100vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        justifyContent:'center',
        flexDirection: 'row',
        backgroundColor: '#eeeff1',
        overflowX:'hidden',
        //border:'1px solid red',
        //backgroundColor: 'black'
    },
    headBar:{
        height: '15vh',
        width: '84vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        justifyContent:'center',
        flexDirection: 'column',
        backgroundColor: 'white',
        //border:'1px solid red',
        border:'4px solid #eeeff1'
    },
    adminContainer:{
        height: '85vh',
        width: '84vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        justifyContent:'center',
        flexDirection: 'row',
        //backgroundColor: '#eeeff1',
        //backgroundColor: 'red',
        border:'4px solid #eeeff1'
    },
    tottalCard:{
        height: '30vh',
        width: '84vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        justifyContent:'center',
        flexDirection: 'row',
        backgroundColor: 'white',
        borderRadius:'15px',
        //border:'1px solid red',
        border:'4px solid #eeeff1'
    },
    card:{
        height: '55vh',
        width: '84vw',
        backgroundColor: 'white',
        borderRadius:'15px',
        border:'4px solid #eeeff1',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        justifyContent:'center',
        flexDirection: 'column',
    },
    subTotalCard:{
        height: '25vh',
        width: '27vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        justifyContent:'center',
        flexDirection: 'column',
    },
    minSubTotalCrd:{
        width:'25vw',
        height:'23vh',
        backgroundColor: 'red',
        borderRadius:'15px',
        backgroundColor:'#eeeff1',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        justifyContent:'center',
        flexDirection: 'column',
    },
    cardDetail:{
        width:'25vw',
        height:'11.5vh',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        justifyContent:'center',
        flexDirection: 'column',
    }
}