export const styleSheet = {
    container: {
        //border:'1px solid red',
        //overflowX:'hidden',
        // marginLeft:'250px',
        // overflowX:'hidden',
        // overflowY:'hidden'
    },
    searchBar: {
        height: '10vh',
        width: '84vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        //border:'1px solid red',
       
    },
    customerContainer:{
        height: '90vh',
        width: '84vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
        //border:'1px solid red',
    },
    profile:{
        height: '85vh',
        width: '32.1vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        justifyContent:'center',
        flexDirection: 'row',
        borderRadius:'15px',
        backgroundColor: '#eeeff1',
        marginLeft:'15px'
    },
    details:{
        height: '93vh',
        width: '50vw',
        display: 'flex',
        alignItems: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        borderRadius:'15px',
        //backgroundColor: 'red',
        marginLeft:'15px'
    },
    textContainer:{
        height: '49vh',
        width: '49vw',
        display: 'flex',
        alignItems: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    subTextContainer:{
        height: '49vh',
        width: '25vw',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        alignItems: 'center',
        justifyContent: 'center',
    },
    image:{
        height: '40vh',
        width: '49vw',
        display: 'flex',
        marginTop:'-60px',
        alignItems: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
       
    }
}