import CarWebsite1 from "../../assets/img/CarWebsite1.png";
import about from "../../assets/img/about.png"

export const stylesSheet ={

    container:{
        overflowX:'hidden',
    },
    homeContainer:{
        height: '100vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundImage: `url(${CarWebsite1})`,
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover',
    },
    navigationBar:{
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        height: '8vh',
        width:'100vw',
        padding:'15px',
        backgroundColor:'transparent',
        alignItems:'center',
        justifyContent:'left'
    },
    bodyContainer:{
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        height: '90vh',
        width: '100vw',
    },
    mainName:{
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        height: '55%',
        width: '50%',
        //border:'1px solid black',
        marginTop: '60px',
        //alignItems:'center',
        //justifyContent:'center'
    },
    selectDate:{
        display: 'flex',
        flexWrap: 'wrap',
        height: '20%',
        width: '65%',
        marginTop:'105px',
        //border:'1px solid red',
        alignItems:'center',
        justifyContent:'center',
    },
    fixDate:{
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        height: '13vh',
        width: '65vw',
        //backgroundColor: '#daddda',
        backgroundColor: 'white',
        border:'1px solid #e7e4e7',
        borderRadius:'15px',
        //opacity:'68%',
        marginLeft:'10px',
        alignItems:'center',
        justifyContent:'center',
    },
    serviceContainer:{
        height: '100vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: '#eeeff1',
    },
    nameContainer:{
        height: '20vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor: '#eeeff1',
        //backgroundColor:'yellow'
    },
    stepContainer:{
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        height: '80vh',
        width: '100vw',
        //backgroundColor: '#daddda',
        //backgroundColor:'green'
    },
    threeStep:{
        display: 'flex',
        height: '80vh',
        width: '33vw',
        //border: '1px solid red',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor: '#eeeff1',
    },
    stepCard:{
        display: 'flex',
        height: '60vh',
        width: '30vw',
        flexDirection: 'column',
        flexWrap: 'wrap',
        backgroundColor: 'white',
        borderRadius:'15px',
        alignItems:'center',
        justifyContent:'center',
    },
    rideContainer:{
        height: '140vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: '#eeeff1',
    },
    carContainer:{
        height: '120vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        //backgroundColor:'green'
    },
    carCard:{
        height: '120vh',
        width: '33vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        //backgroundColor:'white',
        alignItems:'center',
        justifyContent:'center',
    },
    carPackge:{
        display: 'flex',
        width:'200px',
        height:'32px',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems:'left',
        justifyContent:'center',
    },
    carImage:{
        height: '50vh',
        width: '33vw',
        display: 'flex',
        alignItems:'center',
        justifyContent:'center',
        //backgroundColor:'green'
    },
    aboutContainer:{
        height: '100vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        backgroundColor: '#eeeff1',
    },
    aboutImg:{
        display: 'flex',
        height: '80vh',
        width: '50vw',
        alignItems:'center',
        justifyContent:'center',
        //backgroundColor:'green'
    },
    aboutText:{
        //display: 'flex',
        height: '80vh',
        width: '50vw',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems:'center',
        justifyContent:'left',
    },
    reviewContainer:{
        height: '100vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        backgroundColor: '#eeeff1',
    },
    reviewNameContainer:{
        height: '15vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor: '#eeeff1',
        //backgroundColor:'yellow'
    },
    reviewCard:{
        height: '85vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems:'center',
        justifyContent:'center',

    },
    cards:{
        height: '80vh',
        width: '90vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems:'center',
        justifyContent:'center',
    },
    customerCard:{
        height: '80vh',
        width: '30vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems:'center',
        justifyContent:'center',
    },
    subCards:{
        display: 'flex',
        flexDirection: 'row',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'white',
        height: '60vh',
        width: '28vw',
        borderRadius:'15px'
    },
    customerImg:{
        borderRadius:'180px',
        height:'130px',
        width:'125px',
        marginTop:'-240px'
    },
    start:{
        height:'30px',
        width:'200px',
        display: 'flex',
        flexDirection: 'row',
        marginLeft:'-50px',
        marginTop:'20px',
        alignItems:'center',
        justifyContent:'center',
        //border: '1px solid red'
    },
    PopContainer:{
        width:'40vw',
        height:'80vh',
        display: 'flex',
        flexDirection: 'row',
        flexWrap:'wrap',
        alignItems:'center',
        justifyContent:'center',
        //backgroundColor:'red',
        marginTop:'-73px',
        overflowY:'hidden',
        overflowX:'hidden'
    },
    textContainer:{
        width:'40vw',
        height:'60vh',
        display: 'flex',
        flexDirection: 'column',
        flexWrap:'wrap',
        alignItems:'center',
        justifyContent:'center',
        //backgroundColor:'black'
        
    },
    textDetail:{
        width:'20vw',
        height:'60vh',
        display: 'flex',
        flexDirection: 'column',
        flexWrap:'wrap',
        alignItems:'center',
        justifyContent:'center',
        //border: '1px solid red'
    },
    btnContainer:{
        width:'40vw',
        height:'10vh',
        display: 'flex',
        flexDirection: 'column',
        flexWrap:'wrap',
        alignItems:'center',
        justifyContent:'center',
        //border: '1px solid red'
    }
}