export const styleSheet ={
    container:{
        height: '100vh',
        width: '100vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        backgroundColor: '#eeeff1',
        justifyContent: 'center',
        //border: '2px solid #eeeff1',
    },
    subContainer:{
        height: '90vh',
        width: '43vw',
        borderRadius:'15px',
        //border: '1px solid black',
        backgroundColor: 'white',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    uploadPhoto:{
        height: '30vh',
        width: '43vw',
        borderRadius:'15px',
        //border: '1px solid black',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    form:{
        height: '60vh',
        width: '43vw',
        borderRadius:'15px',
        //border: '1px solid black',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    }
}