export const styleSheet = {
    container: {
        height:'100vh',
        width:'83.5vw',
        marginLeft:'9px',
        overflowX:'hidden',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchBar: {
        height: '15vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    bookingPanel: {
        height: '15vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        //backgroundColor: 'yellow',
    },
    vehicleCard:{
        height: '85vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    vehiclePhoto:{
        height: '83vh',
        width: '32vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor:'#eeeff1',
        borderRadius:'15px',
    },
    vehicleForm:{
        height: '83vh',
        width: '50vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    }
}