export const styleSheet = {
    container: {
        height:'100vh',
        width:'83.5vw',
        marginLeft:'9px',
        overflowX:'hidden',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: '#eeeff1',
        alignItems: 'center',
        justifyContent: 'center',
        // marginLeft:'250px',
        // overflowX:'hidden',
        // overflowY:'hidden'
    },
    searchBar: {
        height: '10vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    bookingPanel: {
        height: '10vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        //backgroundColor: 'yellow',
    },
    vehicleCard:{
        height: '115vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #eeeff1',
    },
    vehicleDetail:{
        height: '70vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        //backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
    },
    vehicleTable:{
        height: '45vh',
        width: '83.3vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop:'70px'
    },
    vehiclePhoto:{
        height: '70vh',
        width: '32vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor:'#eeeff1',
        borderRadius:'15px',
        marginBottom:'100px',
        marginLeft:'10px',
        marginTop:'40px'
    },
    vehicleForm:{
        height: '80vh',
        width: '50vw',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    app:{
        height: '70vh',
        width: '82.5vw',
        fontFamily: 'sans-serif',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        flexDirection: 'row',
        //backgroundColor:'red',
        marginBottom:'200px',
    },
    appItem:{
        height: '400px',
        width:'350px',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom:'-20px',
        borderRadius:'15px',
        backgroundColor: '#eeeff1',
    },
}